### ISSUE TITLE
system task does not check if docker group exists

### ISSUE THREAD

**Issue by mofrisch** [ct-Open-Source/telerec-t-base#3]
the following should be added before task "Create docker directory"

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

**Comment by andi-blafasl** [comment]
I'm also facing the problem with the docker directory. I think creating the directory before installing docker with the role from 'geerlingguy.docker' is wrong.
The initial-setup.yml is stoping after the error with the missing group and docker is never installed on my test system.
Fixing this in a proper way would be nice.

**Comment by diankov** [comment]
A added a task to create the group `docker` right before the task which creates the directory:

```
# roles/system/tasks/main.yml
- name: Create docker group
  group:
    name: docker
    state: present
  become: true
  become_method: sudo
  tags: [ always ]
```
