### ISSUE TITLE
portainer overwrites traefik

### ISSUE THREAD

**Issue by DanielK990** [ct-Open-Source/telerec-t-base#6]
If I install each of the four services separately, everything works fine.

But when I run system-setup.yml (in the article erroneously called server-setup.yml), the portainer installation seems to use the service_cfg of traefik.

The traefik/docker-compose.yml contains the content of the portainer compose file and the installation fails because "admin_user" variable cannot be found (I assume because ansible searches for this variable below the traefik section).

The problem also appears for other services, e.g. when I only install watchtower and autoheal - then autoheal overwrites the docker-compose.yml of watchtower.

Really weird - can somebody reproduce this? 

I am suspecting the use of set_fact in facts.yml of compose_hull, but I am not sure.

**Comment by rogue73** [comment]
I've noticed the same behavior on my side. I agree that the misinterpreting of the variables happen within compose_hull. But currently i haven't debug it in detail.

**Comment by nameless66** [comment]
The problem is, When using vars: within the roles: section of a playbook, the variables are added to the play variables, making them available to all tasks within the play before and after the role. This behavior can be changed by [DEFAULT_PRIVATE_ROLE_VARS](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-private-role-vars).
 [see ](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#using-roles-at-the-play-level)

But setting private_role_vars = True in ansible.cfg did't work.

So here is my working system-setup.yml:
````
---
- hosts: server
  become: true
  tasks:
    - name: Set service_cfg to traefik
      set_fact:
        service_cfg: "{{ traefik }}"
    - name: Deploy Traefik
      include_role:
        name: traefik
    - name: Set service_cfg to watchtower
      set_fact:
        service_cfg: "{{ watchtower }}"
    - name: Deploy Watchtower
      include_role:
        name: watchtower
    - name: Set service_cfg to autoheal
      set_fact:
        service_cfg: "{{ autoheal }}"
    - name: Deploy Autoheal
      include_role:
        name: autoheal
    - name: Set service_cfg to portainer
      set_fact:
        service_cfg: "{{ portainer }}"
    - name: Deploy Portainer
      include_role:
        name: portainer
````
